#!/usr/bin/env bash
# ============================================================================
# SSH Apple Watch Gatekeeper Setup (via Secretive)
# ============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

print_status() { echo -e "${BLUE}[INFO]${NC} $1"; }
print_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
print_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
print_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Configuration
SSH_DIR="$HOME/.ssh"
SSH_CONFIG="$SSH_DIR/config"
PRIVATE_ZSHRC="$HOME/.zsh_private_aliases"

# Secretive Paths
SECRETIVE_AGENT="$HOME/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/socket.ssh"
SECRETIVE_PUB_DIR="$HOME/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/PublicKeys"
SECRETIVE_PUB="" # Will be auto-detected

declare -gA SERVER_HOSTS
declare -gA SERVER_USERS
declare -gA SERVER_PORTS

# 1. Parse server definitions
parse_servers() {
    print_status "Parsing SSH server definitions from $PRIVATE_ZSHRC..."
    while IFS= read -r line; do
        if [[ "$line" =~ ^alias\ ([a-zA-Z0-9_-]+)=\'ssh\ (.*)\' ]]; then
            local alias_name="${BASH_REMATCH[1]}"
            local ssh_args="${BASH_REMATCH[2]}"
            local port="22"
            
            if [[ "$ssh_args" =~ -p\ ([0-9]+) ]]; then port="${BASH_REMATCH[1]}"; fi
            
            if [[ "$ssh_args" =~ ([a-zA-Z0-9._-]+)@([a-zA-Z0-9.-]+) ]]; then
                SERVER_USERS["$alias_name"]="${BASH_REMATCH[1]}"
                SERVER_HOSTS["$alias_name"]="${BASH_REMATCH[2]}"
                SERVER_PORTS["$alias_name"]="$port"
                print_status "Found server: $alias_name"
            fi
        fi
    done < "$PRIVATE_ZSHRC"
}

# 2. Verify Secretive Setup & Auto-Detect Key
verify_secretive() {
    print_status "Checking Secretive configuration..."
    
    if [[ ! -S "$SECRETIVE_AGENT" ]]; then
        print_error "Secretive SSH Agent is not running."
        print_warning "Please ensure Secretive is open and running in your menu bar."
        exit 1
    fi

    # Auto-detect the .pub file generated by Secretive
    if [[ -d "$SECRETIVE_PUB_DIR" ]]; then
        SECRETIVE_PUB=$(ls -1 "$SECRETIVE_PUB_DIR"/*.pub 2>/dev/null | head -n 1)
    fi

    if [[ -z "$SECRETIVE_PUB" || ! -f "$SECRETIVE_PUB" ]]; then
        print_error "No Secretive Public Key found in $SECRETIVE_PUB_DIR"
        print_warning "Please open Secretive and create a key first."
        exit 1
    fi
    
    print_success "Secretive agent running. Auto-detected key: $(basename "$SECRETIVE_PUB")"
}

# 3. Configure Mac SSH Client
configure_ssh_client() {
    print_status "Configuring SSH to route through Apple Watch (Secretive)..."
    touch "$SSH_CONFIG"
    
    if ! grep -q "IdentityAgent $SECRETIVE_AGENT" "$SSH_CONFIG"; then
        echo -e "\n# Apple Watch Authentication via Secretive" >> "$SSH_CONFIG"
        echo "Host *" >> "$SSH_CONFIG"
        echo "  IdentityAgent $SECRETIVE_AGENT" >> "$SSH_CONFIG"
        print_success "Global IdentityAgent configured."
    fi

    for alias_name in "${!SERVER_HOSTS[@]}"; do
        local host="${SERVER_HOSTS[$alias_name]}"
        local user="${SERVER_USERS[$alias_name]}"
        local port="${SERVER_PORTS[$alias_name]}"

        if ! grep -q "Host $alias_name" "$SSH_CONFIG"; then
            echo -e "\nHost $alias_name" >> "$SSH_CONFIG"
            echo "  HostName $host" >> "$SSH_CONFIG"
            echo "  User $user" >> "$SSH_CONFIG"
            echo "  Port $port" >> "$SSH_CONFIG"
        fi
    done
}

# 4. Push the Secretive Key to Proxmox
provision_servers() {
    print_status "Pushing Secure Enclave key to servers..."
    
    for alias_name in "${!SERVER_HOSTS[@]}"; do
        local host="${SERVER_HOSTS[$alias_name]}"
        local user="${SERVER_USERS[$alias_name]}"
        local port="${SERVER_PORTS[$alias_name]}"

        print_status "Pushing to $alias_name ($user@$host)..."
        ssh-copy-id -f -i "$SECRETIVE_PUB" -p "$port" -o StrictHostKeyChecking=accept-new "$user@$host" || {
            print_warning "Failed to push key to $alias_name."
        }
    done
    print_success "Server provisioning complete."
}

main() {
    echo -e "${CYAN}╔══════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${CYAN}║         Apple Watch SSH Gatekeeper Setup (Secretive)         ║${NC}"
    echo -e "${CYAN}╚══════════════════════════════════════════════════════════════╝${NC}"
    
    verify_secretive
    parse_servers
    configure_ssh_client
    
    read -p "Push your Apple Watch key to your servers now? (Y/n): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Nn]$ ]]; then
        provision_servers
    fi
    
    print_success "Setup complete! Try SSHing into a server to test the Apple Watch prompt."
}

main "$@"