#!/usr/bin/env bash

# SSH Apple Watch Authentication Setup Script (Fixed)
# Part of dotfiles configuration

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Configuration
SSH_KEY_NAME="id_ecdsa_se"
SSH_DIR="$HOME/.ssh"
SSH_KEY_PATH="$SSH_DIR/$SSH_KEY_NAME"
SSH_CONFIG="$SSH_DIR/config"
PRIVATE_ZSHRC="$HOME/.zsh_private_aliases" # Fixed filename

DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

print_status() { echo -e "${BLUE}[INFO]${NC} $1"; }
print_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
print_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
print_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Parse server definitions from private aliases
parse_servers_from_zshrc() {
    declare -gA SERVER_HOSTS
    declare -gA SERVER_USERS
    declare -gA SERVER_PORTS
    
    if [[ ! -f "$PRIVATE_ZSHRC" ]]; then
        print_error "Private aliases not found at $PRIVATE_ZSHRC"
        exit 1
    fi
    
    print_status "Parsing SSH server definitions from $PRIVATE_ZSHRC..."
    
    while IFS= read -r line; do
        # Look for alias definitions that use ssh
        if [[ $line =~ ^alias\ ([a-zA-Z0-9_-]+)=\'ssh\ (.*)\' ]]; then
            local alias_name="${BASH_REMATCH[1]}"
            local ssh_args="${BASH_REMATCH[2]}"
            
            # Default values
            local port="22"
            local user_host=""
            
            # Extract port if -p is used
            if [[ $ssh_args =~ -p\ ([0-9]+) ]]; then
                port="${BASH_REMATCH[1]}"
            fi
            
            # Extract user@host (gets the last word in the ssh arguments)
            user_host=$(echo "$ssh_args" | awk '{print $NF}')
            
            if [[ $user_host == *@* ]]; then
                local user="${user_host%%@*}"
                local host="${user_host##*@}"
                
                SERVER_HOSTS["$alias_name"]="$host"
                SERVER_USERS["$alias_name"]="$user"
                SERVER_PORTS["$alias_name"]="$port"
                
                print_status "Found server: $alias_name -> $user@$host (Port: $port)"
            fi
        fi
    done < "$PRIVATE_ZSHRC"
    
    if [[ ${#SERVER_HOSTS[@]} -eq 0 ]]; then
        print_warning "No SSH server aliases found in $PRIVATE_ZSHRC"
        exit 1
    fi
    
    print_success "Found ${#SERVER_HOSTS[@]} servers to configure"
}

create_ssh_config() {
    print_status "Creating SSH configuration..."
    
    # Backup existing config if it exists
    [[ -f "$SSH_CONFIG" ]] && cp "$SSH_CONFIG" "$SSH_CONFIG.backup-$(date +%s)"
    
    # Generate new config
    cat > "$SSH_CONFIG" << EOF
# Generated by dotfiles setup-ssh-apple-watch.sh
# $(date)

EOF

    for host in "${!SERVER_HOSTS[@]}"; do
        cat >> "$SSH_CONFIG" << EOF
Host $host
    HostName ${SERVER_HOSTS[$host]}
    User ${SERVER_USERS[$host]}
    Port ${SERVER_PORTS[$host]}

EOF
    done

    # Global Apple Watch Settings
    cat >> "$SSH_CONFIG" << EOF
Host *
    UseKeychain yes
    AddKeysToAgent yes
    IdentityFile ~/.ssh/$SSH_KEY_NAME
    ServerAliveInterval 60
    ServerAliveCountMax 3
EOF

    chmod 600 "$SSH_CONFIG"
    print_success "SSH config created/updated with Apple Watch support."
}

# (You would paste your check_macos, check_apple_watch, generate_ssh_key functions here)

main() {
    echo -e "${BLUE}╔══════════════════════════════════════════════════════════╗${NC}"
    echo -e "${BLUE}║          SSH Apple Watch Authentication Setup            ║${NC}"
    echo -e "${BLUE}╚══════════════════════════════════════════════════════════╝${NC}"
    
    parse_servers_from_zshrc
    create_ssh_config
    
    echo
    print_success "Configuration generated!"
    echo -e "${YELLOW}Next steps:${NC}"
    echo "1. Run ssh-keygen if you don't have an ECDSA/Ed25519 key"
    echo "2. Copy your keys to the servers using ssh-copy-id"
    echo "3. Try connecting: ssh plexms"
}

main "$@"